version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"
      - "80:80"
    links:
      - web
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    image: neurosnap/lists-web
    restart: unless-stopped
    env_file:
      - .env.prod
    links:
      - db
  ssh:
    image: neurosnap/lists-ssh
    restart: unless-stopped
    ports:
      - "22:2222"
    env_file:
      - .env.prod
    links:
      - db
    volumes:
      - ssh_data:/app/ssh_data

volumes:
  db_data:
  caddy_data:
  ssh_data:
  caddy_config:
